backend/WO/Apps/WorkOrdersApp/urls.py
from django.conf.urls import include, url
from .views import DropZoneExample, WorkOrdersListView, NewOrderView, DetailOrderView, EditOrderView

urlpatterns = [
    url(r'^dropzone/$', DropZoneExample.as_view(), name='dropzone'),
    url(r'^work/orders/$', WorkOrdersListView.as_view(), name='work-orders-list'),
    url(r'^new/order/$', NewOrderView.as_view(), name='new-order'),
    url(r'^detail/order/(?P<pk>\d+)/$', DetailOrderView.as_view(), name='detail-order'),
    url(r'^edit/order/(?P<pk>\d+)/$', EditOrderView.as_view(), name='edit-order'),
]

backend/WO/WOP/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Apps.Login.urls')),
    url(r'^administration/', include('Apps.WorkOrdersApp.urls')),
    url(r'^api/', include('Apps.Api.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/WO/Apps/WorkOrdersApp/models.py
#encoding:utf-8
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
import os

class Status(models.Model):
    code = models.CharField(max_length=10)
    description = models.CharField(max_length=20)
    creation_date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Statuses'

    def __str__(self):
        return '%s - %s' % (self.code, self.description)


class Person(models.Model):
    TYPES = (
         (1, 'Coordinator'),
         (2, 'Vendor'),
         (3, 'Employe'),
         (4, 'Client')
    )
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=150)
    state = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    type = models.IntegerField(choices=TYPES)
    status = models.ForeignKey(Status)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Person'
        verbose_name_plural = 'Persons'

    def __str__(self):
        return '%s %s' % (self.first_name, self.last_name)


class Remark(models.Model):
    description = models.TextField()
    status = models.ForeignKey(Status)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Remark'
        verbose_name_plural = 'Remarks'

    def __str__(self):
        return '%s' % (self.description)


class RemarkStatusOrder(models.Model):
    order = models.ForeignKey('Order')
    status = models.ForeignKey(Status)
    remark = models.ForeignKey(Remark)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Remark Status Order'
        verbose_name_plural = 'Remark Status Order'

    def __str__(self):
        return '%s - %s -%s' % (str(self.order.number), self.status.description, self.remark.description)


class Photo(models.Model):
    def get_upload_path(instance, filename):
        carpetaImagenes = slugify('Images/')
        ruta = os.path.join('media/'+carpetaImagenes, str(
            instance.creation_date))
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (slugify(instance.creation_date), ext)
        return os.path.join(ruta, filename)
    photo = models.ImageField(upload_to=get_upload_path)
    status = models.ForeignKey(Status)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'

    def  __str__(self):
        return str(self.creation_date)


class OrderStatusPhoto(models.Model):
    order = models.ForeignKey('Order')
    photo = models.ForeignKey(Photo)
    status = models.ForeignKey(Status)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Order Status Photo'
        verbose_name_plural = 'Orders Status Photos'

    def __str__(self):
        return '%s - %s' % (str(self.order.number), str(self.photo.id))


class Document(models.Model):
    def get_upload_path(instance, filename):
        carpetaImagenes = slugify('Files/')
        ruta = os.path.join('media/'+carpetaImagenes, str(
            instance.creation_date))
        ext = filename.split('.')[-1]
        filename = "%s.%s" % (slugify(instance.creation_date), ext)
        return os.path.join(ruta, filename)

    document = models.FileField(upload_to=get_upload_path)
    status = models.ForeignKey(Status)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Document'
        verbose_name_plural = 'Documents'

    def  __str__(self):
        return str(self.creation_date)


class OrderStatusDocument(models.Model):
    order = models.ForeignKey('Order')
    document = models.ForeignKey(Document)
    status = models.ForeignKey(Status)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Order Status Document'
        verbose_name_plural = 'Orders Status Documents'

    def __str__(self):
        return '%s - %s' % (str(self.order.number), str(self.document.id))


class Order(models.Model):
    number = models.CharField(max_length=50)
    start_date = models.DateField(auto_now_add=False)
    end_date = models.DateField(auto_now_add=False)
    state = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    coordinator = models.ForeignKey(Person,related_name='coordinator')
    vendor = models.ForeignKey(Person,related_name='vendor')
    vendor_sub_out = models.DecimalField(max_digits=10,decimal_places=2)
    sub_out = models.DecimalField(max_digits=10,decimal_places=2)
    client = models.ForeignKey(Person,related_name='client')
    client_contract = models.CharField(max_length=20)
    status = models.ForeignKey(Status)
    remark = models.ManyToManyField(Remark, through=RemarkStatusOrder)
    creation_date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return '%s' % (self.number)

backend/WO/Apps/WorkOrdersApp/forms.py
from django import forms
from .models import Order


class NewOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields=['start_date','end_date','coordinator','status','number', 'state','address','client','client_contract','vendor','vendor_sub_out','sub_out']


    def clean(self):
        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(NewOrderForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.attrs['class'] = 'form-control'
        self.fields['end_date'].widget.attrs['class'] = 'form-control'
        self.fields['coordinator'].widget.attrs['class'] = 'form-control'
        self.fields['status'].widget.attrs['class'] = 'form-control'
        self.fields['number'].widget.attrs['class'] = 'form-control'
        self.fields['state'].widget.attrs['class'] = 'form-control'
        self.fields['address'].widget.attrs['class'] = 'form-control'
        self.fields['client'].widget.attrs['class'] = 'form-control'
        self.fields['client_contract'].widget.attrs['class'] = 'form-control'
        self.fields['vendor'].widget.attrs['class'] = 'form-control'
        self.fields['vendor_sub_out'].widget.attrs['class'] = 'form-control'
        self.fields['sub_out'].widget.attrs['class'] = 'form-control'

backend/WO/Apps/WorkOrdersApp/views.py
#encoding:utf-8
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.db import transaction
from django.contrib import messages
from .models import  Order, Status, OrderStatusPhoto
from .forms import NewOrderForm
from .utils import NeverCacheMixin

class DropZoneExample(TemplateView):
    "Example of dropzone usage"
    template_name = 'drop_zone_example.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        print('the photo arrived!')
        return super(TemplateView, self).render_to_response(context)


class WorkOrdersListView(NeverCacheMixin, TemplateView):
    "Example of dropzone usage"
    template_name = 'work_orders_list.html'

    def post(self, request, *args, **kwargs):
        context = self.get_context_data()
        print('the photo arrived!')
        return super(TemplateView, self).render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(WorkOrdersListView, self).get_context_data(**kwargs)
        context['orders'] = Order.objects.all()
        context['list_orders'] = 'active'
        context['work_orders'] = 'active'
        return context


class NewOrderView( NeverCacheMixin, CreateView):
    model = Order
    form_class = NewOrderForm
    template_name = 'new_orders_form.html'

    def get_success_url(self):
        return reverse('work-orders-list')


    @transaction.atomic()
    def form_valid(self, form):

        form.instance.user = self.request.user
        object_id = form.save
        messages.success(self.request,"Order created")

        return super(NewOrderView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(NewOrderView, self).get_context_data(**kwargs)
        context['work_orders'] = 'active'
        context['new_orders'] = 'active'
        return context


class DetailOrderView(NeverCacheMixin, DetailView):
    model = Order
    template_name = 'detail_order.html'


    def get_context_data(self, **kwargs):
        status_photo = self.request.GET.get('status_photo')
        status = Status.objects.filter(code__in = [6,7,4,8])
        order_status_photo = OrderStatusPhoto.objects.filter(order = self.object)
        if status_photo:
            order_status_photo = order_status_photo.filter(photo__status_id=status_photo)
        print(order_status_photo)
        context = super(DetailOrderView, self).get_context_data(**kwargs)
        context["list_orders"] = "active"
        context['work_orders'] = 'active'
        context['status'] = status
        context['order_status_photo'] = order_status_photo
        return context


class EditOrderView( NeverCacheMixin, UpdateView):
    model = Order
    form_class = NewOrderForm
    template_name = 'new_orders_form.html'

    def get_success_url(self):
        return reverse('work-orders-list')


    @transaction.atomic()
    def form_valid(self, form):
        object_id = form.save
        messages.success(self.request,"Edited order")

        return super(EditOrderView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(EditOrderView, self).get_context_data(**kwargs)
        context['work_orders'] = 'active'
        context['new_orders'] = 'active'
        return context

backend/WO/Apps/WorkOrdersApp/templates/detail_order.html
{% extends 'base.html' %}
{% block title %}
    {{ block.super }} | Detail Order
{% endblock %}
{% block title_conten %}
    Detail Order
{% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    <li><a href="{% url 'work-orders-list' %}"> Orders List</a></li>
    <li class="active">Detail Order</li>
{% endblock %}
{% block contenedor %}
<div class="row">
    <!--/.col (right) -->
    <div class="col-md-5">
      <!-- Widget: user widget style 1 -->
      <div class="box box-widget widget-user">

        <div class="box-footer no-padding">
          <ul class="nav nav-stacked">
            <li><a href="#">Wo #:<span class="pull-right">{{ order.number }}</span></a></li>
            <li><a href="#">Status:<span class="pull-right">{{ order.status }}</span></a></li>
            <li><a href="#">Client:<span class="pull-right">{{ order.client }}</span></a></li>
            <li><a href="#">Vendor:<span class="pull-right">{{ order.vendor }}</span></a></li>
          </ul>
        </div>
      </div>
      <!-- /.widget-user -->
    </div>
    <div class="col-md-6">
      <!-- USERS LIST -->
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Property Photos</h3>

          <div class="box-tools pull-right">
              <span class="label label-success">{{ order_status_photo.count }} imagenes</span>
              <select id="status_photo">
                  <option value="">seleccione una opción</option>
                  {% for status in status %}
                    <option value="{{ status.id }}">{{ status.description }}</option>
                  {% endfor %}
                    <option value="">Todas</option>
              </select>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body no-padding">
          <ul class="users-list clearfix">
           {% for image in order_status_photo %}
            <li>
              <img src="{{ MEDIA_URL }}{{ image.photo.photo }}" alt="User Image">
              <a class="users-list-name" href="#" data-toggle="modal" data-target="#myModalEliminarImagen" onclick="setImgEliminar('{{ MEDIA_URL }}{{ image.photo.photo }}','{{ img.id }}')">Eliminar</a>
              <span class="users-list-date">{{ image.creation_date }}</span>
            </li>
            {% empty %}
                <li>
                    No photos
                </li>
            {% endfor %}
          </ul>
          <!-- /.users-list -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer text-center">
          <a href="#" class="uppercase" data-toggle="modal" data-target="#myModalAgregarFoto"   title="Agregar una nueva imagen.."><i class="fa fa-fw fa-plus"></i></a>
        </div>
        <!-- /.box-footer -->
      </div>
      <!--/.box -->
    </div>
    <!-- /.col -->
</div>
<div class="row">
    <div class="col-md-5">
      <!-- USERS LIST -->
      <div class="box box-danger">
        <div class="box-header with-border">
          <h3 class="box-title">Property Documents</h3>

          <div class="box-tools pull-right">
              <span class="label label-success">{{ order.orderstatusdocument_set.all.count }} Documents</span>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body no-padding"><br>
        {% for p in order.orderstatusdocument_set.all %}
          <a href="{{ MEDIA_URL }}{{ p.document.document }}" target="_blank" class="btn btn-app">
            <i class="fa fa-file-archive-o"></i> {{ p.document.document.name  }}
          </a>
        {% empty %}
            No Files
        {% endfor %}
          <!-- /.users-list -->
        </div>
        <!-- /.box-body -->
        <div class="box-footer text-center">
          <a href="#" class="uppercase" data-toggle="modal" data-target="#myModalAgregarFoto"   title="Agregar una nueva imagen.."><i class="fa fa-fw fa-plus"></i></a>
        </div>
        <!-- /.box-footer -->
      </div>
      <!--/.box -->
    </div>
    <!-- /.col -->

  </div>

  <!-- /.row -->
<div class="modal fade" id="myModalForm" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel" style="text-align: center">Motivo por el cual se inactivara el espacio</h4>
      </div>
      <div class="modal-body">
        <form id="forMotivo">
          <div class="form-group">
            <label for="message-text" class="control-label">Motivo:</label>
              <textarea class="form-control required" id="motivo"></textarea>
              <input type="hidden" id="espacio_id" value="{{ espacio.id }}">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="inactivarB">Inactivar</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="myModalAgregarFoto" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel" style="text-align: center">Select photo</h4>
      </div>
      <div class="modal-body">
        <form id="forImagenSave" enctype="multipart/form-data" method="post">
          <div class="form-group">
            <label for="message-text" class="control-label">Imagen:</label>
            <input type="file" name="imagen" class="form-control required">
            <input type="hidden" name="espacio" value="{{ espacio.id }}">
              <input type="hidden" name="usuario" value="{{ request.user.id }}">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" id="imagenSave">Enviar</button>
      </div>
    </div>
  </div>
</div>


<div class="modal fade" id="myModalEliminarImagen" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel" style="text-align: center">¡Alerta !</h4>
      </div>
      <div class="modal-body">
        <form>
          <div class="form-group">
            <label for="message-text" class="control-label">Esta seguro de eliminar la siguiente imagen:</label>

            <div id="imgEliminar"></div>
              <input type="hidden" id="imagen_id" value="">
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
        <button type="button" class="btn btn-primary" id="imagenEliminar">Eliminar</button>
      </div>
    </div>
  </div>
</div>
{% endblock contenedor %}
{% block extrajs %}
    <script>
        var status_photo = $("#status_photo");

        function setImgEliminar(img, imagen_id) {
            $("#imagen_id").val(imagen_id)
            $("#imgEliminar").html("")
            $("#imgEliminar").append("<img style='width: 570px;' src='"+img+"'>")
        }

        status_photo.change(function () {
          window.location.href="{% url 'detail-order' order.id %}?status_photo="+status_photo.val();
        });
    </script>
{% endblock %}

backend/WO/Apps/WorkOrdersApp/templates/drop_zone_example.html
{% extends 'base.html' %}
{% block contenedor %}
<form action="{% url "dropzone" %}" class="dropzone" method="post" enctype="multipart/form-data">
     {% csrf_token %}
  <div class="fallback" id="example">
    <input name="file" type="file" multiple />
  </div>
</form>
{% endblock contenedor %}
{% block extrajs %}
    <script>
    $("div#example").dropzone({ url: "{% url "dropzone" %}" });
    </script>
{% endblock %}

backend/WO/Apps/WorkOrdersApp/templates/new_orders_form.html
{% extends 'base.html' %}
{% block title %}
    {{ block.super }} | New Orders
{% endblock %}
{% block title_conten %}
    {% if order %}
        Edit Order
    {% else %}
        New Order
    {% endif %}
{% endblock %}
{% block breadcrumb %}
    {{ block.super}}
    {% if order %}
        <li class="active">Edit Order</li>
    {% else %}
        <li class="active">New Order</li>
    {% endif %}
{% endblock breadcrumb %}
{% block contenedor %}
<div class="row">
    <!-- right column -->
    <div class="col-md-12">
      <!-- Horizontal Form -->
      <div class="box box-info">
        <div class="box-header with-border">
            Required fields are marked <b style="color: red;">*</b>
        </div>
        <!-- /.box-header -->
        <!-- form start -->
        <form role="form" id="form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {% include "form_snippet.html" %}
          <!-- /.box-body -->
          <div class="box-footer">

            {% if order %}
                <a href="{% url 'work-orders-list' %}" class="btn btn-warning">Cancelar</a>
            {% endif %}
            <button type="submit" class="btn btn-info pull-right">Enviar</button>
          </div>
          <!-- /.box-footer -->
        </form>
      </div>
      <!-- /.box -->
    </div>
    <!--/.col (right) -->
  </div>
  <!-- /.row -->
{% endblock contenedor %}
{% block extrajs %}
    <script>
    $("div#example").dropzone({ url: "{% url "dropzone" %}" });
    $( "#id_start_date,#id_end_date" ).datepicker({
        format:'yyyy-m-dd'
    }).attr('readonly',true);
    </script>
{% endblock %}

backend/WO/Apps/WorkOrdersApp/templates/work_orders_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}
    {{ block.super }} | Orders List
{% endblock %}
{% block title_conten %}
    Work Orders
{% endblock %}
{% block breadcrumb %}
    {{ block.super }}
    <li class="active">Orders List</li>
{% endblock %}
{% block contenedor %}

<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
              <h3 class="box-title">List</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <table id="work-orders" class="table table-bordered table-striped">
                <thead>
                <tr>
                  <th>ID</th>
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Coordinator</th>
                  <th>Wo Status</th>
                  <th>Wo</th>
                  <th>Estate</th>
                  <th>Adres</th>
                  <th>Client</th>
                  <th>Client Contract</th>
                  <th>Vendor</th>
                  <th>Vendor Sub-out</th>
                  <th>Sub-out%</th>
                  <th></th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                  <th>ID</th>
                  <th>Start Date</th>
                  <th>End Date</th>
                  <th>Coordinator</th>
                  <th>Wo Status</th>
                  <th>Wo</th>
                  <th>Estate</th>
                  <th>Adres</th>
                  <th>Client</th>
                  <th>Client Contract</th>
                  <th>Vendor</th>
                  <th>Vendor Sub-out</th>
                  <th>Sub-out%</th>
                  <th></th>
                </tr>
                </tfoot>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
    </div>
    <!-- /.col -->
</div>
<!-- /.row -->
{% endblock contenedor %}
{% block extrajs %}
    <script>
    $(function () {
        dataTableElement('work-orders','{% url 'api-work-orders-list' %}');

    });
    </script>
{% endblock %}